<h3>Список товаров</h3>
<table class="table">
    <thead>
        <tr>
            <th>Название</th>
            <th>Описание</th>
            <th>Цена</th>
            <th>Действие</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->storeProducts as $product) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($product->name); ?></td>
            <td><?php $str = rtrim(substr($product->desc, 0, 100), '!,.-');
                echo $this->escapeHtml(substr($str, 0, strrpos($str, ' '))) . '...'; ?></td>
            <!--<td><?php// echo $this->escapeHtml($product->desc); ?></td>-->
            <td><?php echo $this->escapeHtml($product->cost); ?></td>
            <td><a href="<?php echo $this->url(NULL, [
                    'controller' => 'store',
                    'action' => 'productDetail',
                    'id' => $product->id
                ]); ?>">Подробней</a> | <a href="<?php echo $this->url(NULL, [
                    'controller' => 'store',
                    'action' => 'shoppingCart',
                    'id' => $product->id
                ]); ?>">В корзину</a></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>