<h2>Товар</h2>
<div>
    <p><b><?php echo $this->escapeHtml($this->storeProduct->name); ?></b></p>
    <p><?php echo $this->escapeHtml($this->storeProduct->desc); ?></p>
    <p><?php echo $this->escapeHtml($this->storeProduct->cost); ?></p>
    
<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url(NULL, ['controller' => 'store', 'action' => 'shoppingCart', 'id' => $this->storeProduct->id]));
$form->setAttribute('method', 'POST');

echo $this->form()->openTag($form);
?>
    <table class="table">
        <tr>
            <td><?php echo $this->formLabel($form->get('qty')); ?></td>
            <td>
                <?php
                echo $this->formElement($form->get('qty'));
                echo $this->formElementErrors($form->get('qty'));
                ?>
            </td>
        </tr>
        <tr>
            <td>&nbsp;</td>
            <td>
                <?php
                echo $this->formElement($form->get('submit'));
                echo $this->formElementErrors($form->get('submit'));
                echo $this->formElement($form->get('store_product_id'));
                ?>
            </td>
        </tr>
    </table>  
<?php echo $this->form()->openTag($form); ?>
</div>