<?php
//js jquery
$this->headScript()->appendFile($this->basePath() . '/js/jquery.min.js', 'text/javascript');
$this->headScript()->appendFile($this->basePath() . '/js/jquery-ui.min.js', 'text/javascript');
//css jquery-ui
$this->headLink()->appendStylesheet($this->basePath() . '/css/jquery-ui.min.css');
// Инициализация кнопок
$this->headScript()->appendScript(
'$(function() {
    $("a.ui-button").button();
});', 'text/javascript');
?>

<h1>Welcome to Users Module</h1>
<!--<a href="<?php /*echo $this->url(NULL, array(
                    'controller' => 'Login', 
                    'action' => 'index'));*/ ?>">Login</a> |-->
<a href="/users/login" class="ui-button">Login</a>
<a href="/users/register" class="ui-button">New User Registration</a>

