<h3>Document Search</h3>
<?php
// Форма поиска
echo $this->form()->openTag($form);
foreach ($form as $element) {
    echo $this->formElement($element);
    echo $this->formElementErrors($element);
}
echo $this->form()->closeTag($form);

// Результаты поиска
if (count($searchResults)) :
?>
<br>
<h4>Results</h4>
<table style="width: 600px; border: 1px solid #f5f5f5">
    <tr>
        <th style="width: 30%; text-align: left"> Label</th>
        <th style="width: 30%; text-align: left"> Owner</th>
        <th style="text-align: left"> File</th>
    </tr>
<?php foreach ($searchResults as $searchResult) : ?>
    <tr>
        <td><?php echo $searchResult->label; ?></td>
        <td><?php echo $searchResult->owner; ?></td>
        <td><a href="<?php echo $this->url('users/upload-manager', array(
            'action' => 'fileDownload',
            'id' => $searchResult->upload_id
        )); ?>">Download</a></td>
    </tr>
<?php endforeach; ?>
</table>
<?php endif;
