<section class="login">
    <h2>Upload Image</h2>
    <?php if ($this->error): ?>
    <p class="error">
        There were one or more issues with your submission.
        Please correct them as indicated below.
    </p>
    <?php endif; ?>
    
    <?php 
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('action', $this->url(NULL, array('controller'=>'MediaManager', 'action'=>'process')));
    $form->setAttribute('method', 'post');
    $form->setAttribute('class', 'form-horizontal');
    echo $this->form()->openTag($form);
    ?>
    <div class="control-group">
        <?php echo $this->formLabel($form->get('label')); ?>
        <div class="controls">
            <?php echo $this->formElement($form->get('label')); ?>
        </div>
    </div>
    <div class="control-group">
        <?php echo $this->formLabel($form->get('fileupload')); ?>
        <div class="controls">
           <?php 
                echo $this->formElement($form->get('fileupload'));
                echo $this->formElementErrors($form->get('fileupload'));
            ?>
        </div>
    </div>
    <div class="control-group">
        <div class="controls">
           <?php 
                echo $this->formElement($form->get('submit'));
                echo $this->formElementErrors($form->get('submit'));
            ?>
        </div>
    </div>
    <?php echo $this->form()->closeTag(); ?>
    
</section>
