<h3>Управление продуктами</h3>
<table class="table">
    <thead>
        <tr>
            <th>Название</th>
            <th>Описание</th>
            <th>Цена</th>
            <th>Действие</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->storeProducts as $product) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($product->name); ?></td>
            <td><?php $str = rtrim(substr($product->desc, 0, 100), '!,.-');
                echo $this->escapeHtml(substr($str, 0, strrpos($str, ' '))) . '...'; ?></td>
            <!--<td><?php// echo $this->escapeHtml($product->desc); ?></td>-->
            <td><?php echo $this->escapeHtml($product->cost); ?></td>
            <td><a href="<?php echo $this->url('users/store-admin', [
                    'action' => 'index',
                    'id' => $product->id
                ]); ?>">Изменить</a> | <a href="<?php echo $this->url('users/store-admin', [
                    'action' => 'deleteProduct',
                    'id' => $product->id
                ]); ?>" onclick="return confirm('Удалить файл?') ? true : false;">Удалить</a></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<a href="<?php echo $this->url(NULL, array(
		'controller' => 'StoreAdmin', 
		'action' => 'addProduct'
	)); ?>" class="btn">Добавить товар</a>

